import robloxpy
import robloxpy.User.Internal as LocalUser
import robloxpy.Utils as Utils
def PrintData():
    print("UserID: " + str(LocalUser.UserID))
    print("Username: " + str(LocalUser.Username))
    print("Robux: " + str(LocalUser.Robux))
    print("Thumbnail: " + str(LocalUser.Thumbnail))
    print("isBuildersclub: " + str(LocalUser.isBuildersclub))
    print("isPremium: " + str(LocalUser.isPremium))
    print("canChangeUsername: " + str(LocalUser.canChangeUsername))
    print("isAdmin: " + str(LocalUser.isAdmin))
    print("isEmailOnFile: " + str(LocalUser.isEmailOnFile))
    print("isEmailVerified: " + str(LocalUser.isEmailVerified))
    print("isPhoneFeatureEnabled: " + str(LocalUser.isPhoneFeatureEnabled))
    print("isSuperSafePrivacyMode: " + str(LocalUser.isSuperSafePrivacyMode))
    print("IsAppChatSettingEnabled: " + str(LocalUser.IsAppChatSettingEnabled))
    print("IsGameChatSettingEnabled: " + str(LocalUser.IsGameChatSettingEnabled))
    print("IsContentRatingsSettingEnabled: " + str(LocalUser.IsContentRatingsSettingEnabled))
    print("IsParentalControlsTabEnabled: " + str(LocalUser.IsParentalControlsTabEnabled))
    print("IsSetPasswordNotificationEnabled: " + str(LocalUser.IsSetPasswordNotificationEnabled))
    print("ChangePasswordRequiresTwoStepVerification: " + str(LocalUser.ChangePasswordRequiresTwoStepVerification))
    print("ChangeEmailRequiresTwoStepVerification: " + str(LocalUser.ChangeEmailRequiresTwoStepVerification))
    print("UserEmail: " + str(LocalUser.UserEmail))
    print("UserEmailMasked: " + str(LocalUser.UserEmailMasked))
    print("UserEmailVerified: " + str(LocalUser.UserEmailVerified))
    print("CanHideInventory: " + str(LocalUser.CanHideInventory))
    print("CanTrade: " + str(LocalUser.CanTrade))
    print("MissingParentEmail: " + str(LocalUser.MissingParentEmail))
    print("IsUpdateEmailSectionShown: " + str(LocalUser.IsUpdateEmailSectionShown))
    print("IsUnder13UpdateEmailMessageSectionShown: " + str(LocalUser.IsUnder13UpdateEmailMessageSectionShown))
    print("IsUserConnectedToFacebook: " + str(LocalUser.IsUserConnectedToFacebook))
    print("IsTwoStepToggleEnabled: " + str(LocalUser.IsTwoStepToggleEnabled))
    print("AgeBracket: " + str(LocalUser.AgeBracket))
    print("UserAbove13: " + str(LocalUser.UserAbove13))
    print("ClientIpAddress: " + str(LocalUser.ClientIpAddress))
    print("UserAge: " + str(LocalUser.UserAge))
    print("IsBcRenewalMembership: " + str(LocalUser.IsBcRenewalMembership))
    print("IsAccountPinEnabled: " + str(LocalUser.IsAccountPinEnabled))
    print("IsAccountRestrictionsFeatureEnabled: " + str(LocalUser.IsAccountRestrictionsFeatureEnabled))
    print("IsAccountRestrictionsSettingEnabled: " + str(LocalUser.IsAccountRestrictionsSettingEnabled))
    print("IsAccountSettingsSocialNetworksV2Enabled: " + str(LocalUser.IsAccountSettingsSocialNetworksV2Enabled))
    print("InApp: " + str(LocalUser.InApp))
    print("HasFreeNameChange: " + str(LocalUser.HasFreeNameChange))
    print("IsAgeDownEnabled: " + str(LocalUser.IsAgeDownEnabled))
    print("ReceiveNewsletter: " + str(LocalUser.ReceiveNewsletter))

LocalUser.SetCookie("")
print(Utils.TestCookie)
PrintData()
